import Head from "next/head";
import Image from "next/image";
import ProductList from "../components/ProductList/ProductList";
import styles from "../styles/Home.module.css";

const Home = (props) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ProductList products={props.products} />
		</div>
	);
};
export async function getStaticProps() {
	const response = await fetch("https://fakestoreapi.com/products?limit=12");
	const data = await response.json();

	return {
		props: {
			products: data,
		},
		revalidate: 1,
	};
}
export default Home;
