import Head from "next/head";
import { useState } from "react";
import ProductList from "../components/ProductList/ProductList.component";
import styles from "../styles/Home.module.css";

const Home = (props) => {
    const [loading,setLoading]=useState(true);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{loading && <ProductList products={props.products} />}
		</div>
	);
};
export async function getStaticProps() {
	const response = await fetch(process.env.PRODUCT_LIST_FETCH_URL_LIMIT);
	const data = await response.json();

	return {
		props: {
			products: data,
		},
		revalidate: 1000,
	};
}
export default Home;
